<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.softserve</groupId>
    <artifactId>microservice-spring-boot</artifactId>
    <packaging>jar</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>microservice-spring-boot-code-generator</name>
    <url>https://maven.apache.org</url>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.0</version>
    </parent>
    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator.version}</version>
                <executions>
				    <!-- Uncomment execution configuration below if you have a real API spec -->
				    <!--
                    <execution>
                        <id>spring-server</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/api-specs/provided/(SET_PROVIDED_API_NAME_HERE)-api.yaml
                            </inputSpec>
                            <additionalProperties>
                                <annotationApi>jakarta</annotationApi>
                            </additionalProperties>
                            <apiPackage>com.softserve.enterprise.generated.api</apiPackage>
                            <modelPackage>com.softserve.enterprise.generated.model</modelPackage>
                            <generatorName>spring</generatorName>
                            <packageName>com.softserve.enterprise.generated</packageName>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
				    -->			
							<!--  
                                Provides additional configuration options help 
                                <configHelp>true</configHelp>
							-->
                    <!--							
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <openApiNullable>false</openApiNullable>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <serializableModel>true</serializableModel>
                                <snapshotVersion>true</snapshotVersion>
                                <useOptional>true</useOptional>
                                <useJakartaEe>true</useJakartaEe>
                                <useTags>true</useTags>
                            </configOptions>
                        </configuration>
                    </execution>
				    -->
					<!-- Uncomment execution configuration below if you have a real API client -->
					<!--
                    <execution>
                        <id>spring-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <templateDirectory>${project.basedir}/src/main/resources/generator-templates</templateDirectory>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/api-specs/consumed/(SET_CONSUMED_API_NAME_HERE)-api.yaml
                            </inputSpec>
                            <additionalProperties>
                                <annotationApi>jakarta</annotationApi>
                            </additionalProperties>
                            <apiPackage>com.softserve.enterprise.generated.client.api</apiPackage>
                            <modelPackage>com.softserve.enterprise.generated.client.model</modelPackage>
                            <generatorName>java</generatorName>
                            <packageName>com.softserve.enterprise.generated.client</packageName>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <configOptions>
                                <generateApiTests>false</generateApiTests>
                                <generateApiDocumentation>false</generateApiDocumentation>
                                <generateModelTests>false</generateModelTests>
                                <generateModelDocumentation>false</generateModelDocumentation>
                                <library>restclient</library>
                                <openApiNullable>false</openApiNullable>
                                <useJakartaEe>true</useJakartaEe>
                            </configOptions>
                        </configuration>
                    </execution>
					-->
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <proc>none</proc>
                    <release>${java.version}</release>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-restclient</artifactId>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>${swagger-annotations-version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>${jakarta-validation.version}</version>
        </dependency>
        <dependency>
            <groupId>tools.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson-datatype.version}</version>
        </dependency>
    </dependencies>
    <properties>
        <java.version>21</java.version>
        <jakarta-validation.version>3.1.1</jakarta-validation.version>
        <maven-compiler.version>3.14.1</maven-compiler.version>
        <openapi-generator.version>7.18.0</openapi-generator.version>
        <swagger-annotations-version>2.2.37</swagger-annotations-version>
        <jackson-datatype.version>3.0.0-rc2</jackson-datatype.version>
    </properties>
</project>
