plugins:
  # This is sample config structure for component OAuth-Client plugin
  keycloakClient:
    environments:
      - name: ${PLUGINS_KEYCLOAKCLIENT_ENV_0_NAME}
        url: ${PLUGINS_KEYCLOAKCLIENT_ENV_0_URL}
        realm: ${PLUGINS_KEYCLOAKCLIENT_ENV_0_REALM}
        clientId: ${PLUGINS_KEYCLOAKCLIENT_ENV_0_CLIENTID}
        username: ${PLUGINS_KEYCLOAKCLIENT_ENV_0_USERNAME}
        password: ${PLUGINS_KEYCLOAKCLIENT_ENV_0_PASSWORD}
      - name: ${PLUGINS_KEYCLOAKCLIENT_ENV_1_NAME}
        url: ${PLUGINS_KEYCLOAKCLIENT_ENV_1_URL}
        realm: ${PLUGINS_KEYCLOAKCLIENT_ENV_1_REALM}
        clientId: ${PLUGINS_KEYCLOAKCLIENT_ENV_1_CLIENTID}
        username: ${PLUGINS_KEYCLOAKCLIENT_ENV_1_USERNAME}
        password: ${PLUGINS_KEYCLOAKCLIENT_ENV_1_PASSWORD}
      - name: ${PLUGINS_KEYCLOAKCLIENT_ENV_2_NAME}
        url: ${PLUGINS_KEYCLOAKCLIENT_ENV_2_URL}
        realm: ${PLUGINS_KEYCLOAKCLIENT_ENV_2_REALM}
        clientId: ${PLUGINS_KEYCLOAKCLIENT_ENV_2_CLIENTID}
        username: ${PLUGINS_KEYCLOAKCLIENT_ENV_2_USERNAME}
        password: ${PLUGINS_KEYCLOAKCLIENT_ENV_2_PASSWORD}
      - name: ${PLUGINS_KEYCLOAKCLIENT_ENV_3_NAME}
        url: ${PLUGINS_KEYCLOAKCLIENT_ENV_3_URL}
        realm: ${PLUGINS_KEYCLOAKCLIENT_ENV_3_REALM}
        clientId: ${PLUGINS_KEYCLOAKCLIENT_ENV_3_CLIENTID}
        username: ${PLUGINS_KEYCLOAKCLIENT_ENV_3_USERNAME}
        password: ${PLUGINS_KEYCLOAKCLIENT_ENV_3_PASSWORD}
      - name: ${PLUGINS_KEYCLOAKCLIENT_ENV_4_NAME}
        url: ${PLUGINS_KEYCLOAKCLIENT_ENV_4_URL}
        realm: ${PLUGINS_KEYCLOAKCLIENT_ENV_4_REALM}
        clientId: ${PLUGINS_KEYCLOAKCLIENT_ENV_4_CLIENTID}
        username: ${PLUGINS_KEYCLOAKCLIENT_ENV_4_USERNAME}
        password: ${PLUGINS_KEYCLOAKCLIENT_ENV_4_PASSWORD}
  # This is sample config structure for OAuth-PKCE-Token-Generator plugin
  oauthPkceTokenGenerator:
    frontendRoutePath: 'oauth-pkce-token-generator'
    environments:
      - name: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_0_NAME}
        authUrl: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_0_AUTHURL}
        tokenUrl: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_0_TOKENURL}
        clientId: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_0_CLIENTID}
        clientSecret: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_0_CLIENTSECRET}
      - name: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_1_NAME}
        authUrl: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_1_AUTHURL}
        tokenUrl: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_1_TOKENURL}
        clientId: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_1_CLIENTID}
        clientSecret: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_1_CLIENTSECRET}
      - name: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_2_NAME}
        authUrl: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_2_AUTHURL}
        tokenUrl: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_2_TOKENURL}
        clientId: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_2_CLIENTID}
        clientSecret: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_2_CLIENTSECRET}
      - name: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_3_NAME}
        authUrl: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_3_AUTHURL}
        tokenUrl: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_3_TOKENURL}
        clientId: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_3_CLIENTID}
        clientSecret: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_3_CLIENTSECRET}
      - name: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_4_NAME}
        authUrl: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_4_AUTHURL}
        tokenUrl: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_4_TOKENURL}
        clientId: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_4_CLIENTID}
        clientSecret: ${PLUGINS_OAUTHPKCETOKENGENERATOR_ENV_4_CLIENTSECRET}

